services:
  streamlit-app:
    build:
      context: .
      dockerfile: apps/chatbot_ui/Dockerfile
    ports:
      - 8501:8501
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./apps/chatbot_ui/src:/app/apps/chatbot_ui/src

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - TORCH_DYNAMO_DISABLE=1
    restart: unless-stopped
    volumes:
      - ./apps/api/src:/app/apps/api/src

  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./qdrant_data:/qdrant/storage:z
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${MULTI_TURN_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MULTI_TURN_POSTGRES_PASSWORD}
      POSTGRES_DB: ${MULTI_TURN_POSTGRES_DB}
      PGDATA: ${MULTI_TURN_PGDATA}
    restart: unless-stopped
    volumes:
      - ./postgres_data:${MULTI_TURN_PGDATA}

  items-mcp-server:
    build:
      context: .
      dockerfile: apps/items_mcp_server/Dockerfile
    ports:
      - 8001:8000
    env_file:
      - .env
    restart: unless-stopped

  reviews-mcp-server:
    build:
      context: .
      dockerfile: apps/reviews_mcp_server/Dockerfile
    ports:
      - 8002:8000
    env_file:
      - .env
    restart: unless-stopped
