"""Initial schema setup

Revision ID: a174cdfcaf56
Revises: 
Create Date: 2026-08-16 11:10:23.204432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a174cdfcaf56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('previous_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_correlation_id'), 'audit_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_events_id'), 'audit_events', ['id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=False)
    op.create_table('derived_metric_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_period', sa.String(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.Column('calculation_version', sa.String(), nullable=True),
    sa.Column('input_fact_versions', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_derived_metric_values_id'), 'derived_metric_values', ['id'], unique=False)
    op.create_index(op.f('ix_derived_metric_values_metric_name'), 'derived_metric_values', ['metric_name'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('s3_path', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_period', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_index(op.f('ix_documents_fiscal_period'), 'documents', ['fiscal_period'], unique=False)
    op.create_index(op.f('ix_documents_fiscal_year'), 'documents', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('financial_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('concept', sa.String(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_period', sa.String(), nullable=False),
    sa.Column('fiscal_period_start', sa.DateTime(), nullable=True),
    sa.Column('fiscal_period_end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_facts_concept'), 'financial_facts', ['concept'], unique=False)
    op.create_index(op.f('ix_financial_facts_id'), 'financial_facts', ['id'], unique=False)
    op.create_table('source_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('text_snippet', sa.Text(), nullable=True),
    sa.Column('bounding_box', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('object_storage_path', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_locations_id'), 'source_locations', ['id'], unique=False)
    op.create_table('financial_fact_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fact_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), sa.CheckConstraint("origin IN ('AI_GENERATED', 'ANALYST_CORRECTED', 'ANALYST_ENTERED')", name='chk_fact_version_origin'), nullable=False),
    sa.Column('verification_status', sa.String(), sa.CheckConstraint("verification_status IN ('UNVERIFIED', 'VERIFIED')", name='chk_fact_version_verification_status'), nullable=False),
    sa.Column('source_location_id', sa.Integer(), nullable=True),
    sa.Column('change_reason', sa.String(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['fact_id'], ['financial_facts.id'], ),
    sa.ForeignKeyConstraint(['source_location_id'], ['source_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fact_versions_current_uniq', 'financial_fact_versions', ['fact_id'], unique=True, postgresql_where=sa.text('is_current = true'))
    op.create_index(op.f('ix_financial_fact_versions_id'), 'financial_fact_versions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_fact_versions_id'), table_name='financial_fact_versions')
    op.drop_index('ix_fact_versions_current_uniq', table_name='financial_fact_versions', postgresql_where=sa.text('is_current = true'))
    op.drop_table('financial_fact_versions')
    op.drop_index(op.f('ix_source_locations_id'), table_name='source_locations')
    op.drop_table('source_locations')
    op.drop_index(op.f('ix_financial_facts_id'), table_name='financial_facts')
    op.drop_index(op.f('ix_financial_facts_concept'), table_name='financial_facts')
    op.drop_table('financial_facts')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_fiscal_year'), table_name='documents')
    op.drop_index(op.f('ix_documents_fiscal_period'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_derived_metric_values_metric_name'), table_name='derived_metric_values')
    op.drop_index(op.f('ix_derived_metric_values_id'), table_name='derived_metric_values')
    op.drop_table('derived_metric_values')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_audit_events_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_correlation_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
